### ISSUE TITLE
Strange 404

### ISSUE THREAD

**Issue by BenjaminKaul** [styladev/plugin-wordpress#6]
I have implemented the plugin and the magazine works but it shows an 404 directly above the working magazine:
https://summersby.de/start-styla/
Setting the front page as the root for the magazine leads to 404 errors on every other link on the page

**Comment by ssachtleben** [comment]
Hey Benjamin,

we updated our plugin to fix the 404 errors on different pages when magazine runs on startpage. We added previously a new feature that redirect to 404 page when our seoapi explicit returns a 404 code for non existing sites within the magazine. But the magazine was running on a specific path, now since it ran on the startpage all routes where forwarded to seoapi and resolved to 404 page. Now only the real magazine routes are going through the pipeline.

The release can be found here: https://github.com/styladev/plugin-wordpress/releases/tag/v1.2.4

Best,
Sebastian
